-- Replicas --
r0 172.30.0.10
r1 172.30.0.11
r2 172.30.0.12

-- Clients --
c1 172.30.0.100
c2 172.30.0.101

-- Master --
m 172.30.0.5

masterport: 7087

protocol: epaxos
noop: false

reqs: 1000
writes: 100
conflicts: 2
commandsize: 16
clones: 0
key: 42
pipeline: false

-- Proxy --
server_alias r0
c1 (local)
c2
---
